import React from 'react';

const ReportCard: React.FC<{ title: string, description: string, icon: string, lastGenerated: string }> = ({ title, description, icon, lastGenerated }) => (
  <div className="bg-card-dark p-6 rounded-xl border border-border-dark hover:border-primary/40 transition-all group cursor-pointer">
    <div className="bg-primary/10 size-12 rounded-lg flex items-center justify-center text-primary mb-4 group-hover:scale-110 transition-transform">
      <span className="material-symbols-outlined text-2xl">{icon}</span>
    </div>
    <h3 className="text-lg font-bold mb-2">{title}</h3>
    <p className="text-sm text-text-secondary mb-4 line-clamp-2">{description}</p>
    <div className="flex items-center justify-between mt-auto">
      <span className="text-[10px] uppercase font-bold text-slate-500">Last: {lastGenerated}</span>
      <button className="text-primary text-sm font-bold hover:underline flex items-center gap-1">
        Generate <span className="material-symbols-outlined text-sm">arrow_forward</span>
      </button>
    </div>
  </div>
);

const ReportsView: React.FC = () => {
  const reports = [
    { title: 'Financial Performance', description: 'Monthly revenue, expense tracking and churn analysis reports.', icon: 'payments', lastGenerated: 'Oct 24, 2023' },
    { title: 'User Engagement', description: 'Daily active users, retention cohorts and session metrics.', icon: 'analytics', lastGenerated: 'Oct 20, 2023' },
    { title: 'System Health', description: 'Server uptime, API latency and error rate distribution.', icon: 'monitor_heart', lastGenerated: 'Yesterday' },
    { title: 'Marketing Attribution', description: 'Conversion rates by source, campaign ROI and lead quality.', icon: 'campaign', lastGenerated: '2 days ago' },
  ];

  return (
    <div className="p-6 animate-in fade-in duration-500">
      <div className="max-w-[1600px] mx-auto space-y-8">
        <div className="flex justify-between items-end">
          <div>
            <h1 className="text-2xl font-bold text-white">Business Reports</h1>
            <p className="text-text-secondary text-sm">Export and analyze your platform data in multiple formats</p>
          </div>
          <button className="px-4 py-2 bg-white/5 hover:bg-white/10 border border-border-dark rounded-lg text-sm font-bold flex items-center gap-2">
            <span className="material-symbols-outlined text-lg">schedule</span>
            Schedule Auto-reports
          </button>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          {reports.map((r, i) => <ReportCard key={i} {...r} />)}
        </div>

        <div className="bg-card-dark rounded-xl border border-border-dark overflow-hidden">
          <div className="p-6 border-b border-border-dark flex items-center justify-between">
            <h3 className="font-bold">Recent Exports</h3>
            <span className="text-xs text-text-secondary">Last 30 days</span>
          </div>
          <div className="overflow-x-auto">
            <table className="w-full text-left">
              <thead>
                <tr className="bg-white/5 text-[11px] font-bold text-slate-500 uppercase tracking-widest">
                  <th className="py-4 px-6">File Name</th>
                  <th className="py-4 px-6">Category</th>
                  <th className="py-4 px-6">Generated By</th>
                  <th className="py-4 px-6">Date</th>
                  <th className="py-4 px-6 text-right">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-white/5">
                {[1, 2, 3].map((_, i) => (
                  <tr key={i} className="hover:bg-white/[0.02]">
                    <td className="py-4 px-6">
                      <div className="flex items-center gap-3">
                        <span className="material-symbols-outlined text-red-500">picture_as_pdf</span>
                        <span className="text-sm font-medium">Monthly_Revenue_Q4_2023.pdf</span>
                      </div>
                    </td>
                    <td className="py-4 px-6"><span className="px-2 py-0.5 bg-blue-500/10 text-blue-500 rounded text-[10px] font-bold uppercase">Financial</span></td>
                    <td className="py-4 px-6 text-sm">System (Auto)</td>
                    <td className="py-4 px-6 text-sm text-slate-400">Oct 24, 2023</td>
                    <td className="py-4 px-6 text-right">
                      <button className="text-slate-400 hover:text-white"><span className="material-symbols-outlined">download</span></button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ReportsView;